'use strict';

angular.module('driveoutApp.directives', [
  'driveoutApp.directives.bricks',
  'driveoutApp.directives.brickswmo',
  'driveoutApp.directives.donut',
  'driveoutApp.directives.enb',
  'driveoutApp.directives.focus',
  'driveoutApp.directives.image',
  'driveoutApp.directives.peoplelines',
  'driveoutApp.directives.diversityacrossar',
  'driveoutApp.directives.diversitybetweenwgs',
  'driveoutApp.directives.wenn',
  'driveoutApp.directives.partcountrybridgenonbridge',
  'driveoutApp.directives.partratehisto',
  'driveoutApp.directives.partratehistototal',
  'driveoutApp.directives.roledistribstacked',
  'driveoutApp.directives.subchapters',
  'driveoutApp.directives.topmenu',
  'driveoutApp.directives.footer',
  'driveoutApp.directives.zeppelin',
  'driveoutApp.directives.partcountry9010',
  'driveoutApp.directives.roleevolutiondiversity',
  'driveoutApp.directives.diversityacrossroles',
  'driveoutApp.directives.section',
  'driveoutApp.directives.pdfconclusion',
  'driveoutApp.directives.stackedwgsbyar',
  'driveoutApp.directives.stackedwgsbyarcountryvstotal',
  'driveoutApp.directives.stackedwgsbyarcavsnonca',
  'driveoutApp.directives.lastngrepeat',
  'driveoutApp.directives.gexfinstitutions',
  'driveoutApp.directives.unfccctablefive',
  'driveoutApp.directives.unfccctablefour',
  'driveoutApp.directives.unfccctrajectoriesadaptation',
  'driveoutApp.directives.gexftestone'
  ])
